@startuml Instituição

class Pessoa {
    nome: String
    matricula: int
}

class Professor {
    formacao: String
    salario: Double
    ElaboraProva(): void
}

class Aluno {
    dataNascimento: Date
    fazProva(): void
}

class Turma {
    sigla: String
    ano: int
    adicionarAluno(): void
}

class Disciplina {
    nome: String
    cargaHoraria: int
}

Professor --|> Pessoa
Aluno --|> Pessoa
Aluno "1..*" --* "1" Turma 
Professor "1..*" --> "1..*" Disciplina
Disciplina "*" --> "*" Turma


@enduml
